### PR TITLE
Student Delete Endpoint

### LINKED ISSUE #37: Add Delete endpoint for specific record in students table
See #26

### PR DESCRIPTION
**Pull request by blobthebuilder**
## Overview

In this PR, I added the Delete endpoint and tests for students.

## Validation (Optional)

1. Download this branch.
2. Run the project.
3. Go to swagger and test endpoint (hard to test because no post endpoint)

## Dokku link
https://happycows-blobthebuilder.dokku-11.cs.ucsb.edu/

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 

## Linked Issues
Closes #37

### CODE REVIEW

**Review by smmzhu — APPROVED** [review]
lgtm

**Review by smmzhu — APPROVED** [review]
lgtm

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by blobthebuilder** [comment]
I just resolved merge conflicts.

**Pull request merged**
