### PR TITLE
(MERGE PR #38 BEFORE TOUCHING THIS) Form Component for Courses plus test, Create fixtures for Courses (

### LINKED ISSUE #44: Form Component for Courses plus tests

### PR DESCRIPTION
**Pull request by adenjo6**
Deployed here:        https://happycows-adenjo.dokku-11.cs.ucsb.edu

Storybook: https://ucsb-cs156-f24.github.io/proj-happycows-f24-11/prs/50/storybook/?path=/story/components-courses-coursesform--create

## Overview

In this PR, I created the fixtures and Form Components for Courses plus tests

## Screenshots (Optional)
Storybook:
Screenshot 2024-11-25 at 2 34 19 AM
Screenshot 2024-11-25 at 2 35 02 AM
Screenshot 2024-11-25 at 2 35 13 AM

Mutation Tests:

Screenshot 2024-11-25 at 2 35 54 AM

Coverage Tests:
Screenshot 2024-11-25 at 2 40 37 AM

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #44 and #43

### CODE REVIEW

**Review by blobthebuilder — DISMISSED** [review]
LGTM

**Review by smmzhu — DISMISSED** [review]
lgtm

**Comment by adenjo6** [comment]
Note: 
I clicked merge instead of rebase, so my previous PR #38 's 12 files show up here. I will make sure to rebase whenever possible to avoid clutter.

**Review by JohnLins — APPROVED** [review]
LGTM

**Pull request merged**
