### PR TITLE
GetAllByCourseId Endpoint added — GET endpoint for multiple students objects in table

### LINKED ISSUE #32: Add GetAllByCourseId endpoint for all record in students table with certain course ID

### PR DESCRIPTION
**Pull request by smmzhu**
## Overview

(Merge #30 before this one)
Fourth ticket in a series tackling issue #26 — GetAllByCourseId Endpoint added. GET endpoint for multiple students objects with same CourseId.

Testing link [here](https://sampr1.dokku-11.cs.ucsb.edu)

## Screenshots (Optional)
image

## Future Possibilities (Optional)

This endpoint may have to be paginated in the future since the max load could be upwards of 850 students (in the worst case of Campbell Hall).

## Validation (Optional)

1. Go into Swagger. Use the students Post request to create student objects in the table with the same CourseId.
2. Validate this endpoint by using the endpoint to get the student objects back.

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] ~~Frontend Unit tests (`npm test`) pass~~
- [ ] ~~Frontend Test coverage (`npm run coverage`) 100%~~
- [ ] ~~Frontend Mutation tests (`npx stryker run`) 100%~~ 
- [ ] ~~Frontend Linting (`npx eslint --fix src`)~~

## Linked Issues

Closes #32

### CODE REVIEW

**Review by brianc2730 — DISMISSED** [review]
LGTM!

**Review by pconrad — DISMISSED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
Nice work!

**Pull request merged**
